### ISSUE TITLE
How do you respond to failure?

### ISSUE THREAD

**Issue by anthonygarvan** [18F/core-values#7]
Failure is a normal part of innovation, like it or not. It could come from internal sources, like missed deadlines or crippling bugs, or it could come from outside sources, such as dramatically shifting requirements or politics. 

How does 18F respond to big failures, such as a project cancellation? What is the strategy for retaining talent and keeping morale high in these circumstances? How will you learn from these failures as an organization without becoming overly bureaucratic and risk averse?

**Comment by mbland** [comment]
Speaking largely for myself here, and from my perspective, though I'll try to be fair.

We haven't yet had to respond to any big failures yet; the team's only a year and and five months old, been growing quickly, and we take a lot of care to avoid projects where we'd set ourselves up for failure. We've hired from a diverse array of backgrounds and capabilities, giving us the benefit of many different perspectives on every issue we face. Our focus on Open Source and Agile methodologies also help prevent bureaucratic ossification and help us manage risk rather than grow averse to it. Things have held up well so far, but that said, I've been there before and know what you mean.

The most vivid case in my experience was the 2008 crisis. My old company had to let go of contract employees, many of which were manual software testers. Fortunately, thanks to the extremely open internal culture that enabled a bunch of us volunteers to prepare (unknowingly) for this by driving adoption of automated testing throughout the development organization, we were able to weather the storm without a sudden "quality crisis". That wasn't the only thing that kept us afloat, but I will claim it was a significant factor.

Based on that experience, I consider it part of my job, personally, to help prepare 18F for potential future shocks by creating a robust environment based on transparency, autonomy, and collaboration. (And automated testing, but that's not as hard a sell around here.) I created platforms like [the 18F Hub](https://18f.gsa.gov/2014/12/23/hub/), [18F Pages](https://18f.gsa.gov/2015/05/14/18Fpages/), and [18F Guides](https://18f.gsa.gov/2015/05/28/18F-guides/) to foster an environment of access, awareness, and knowledge-sharing, so that we're constantly helping develop one another's knowledge and skills. All this is great for onboarding new team members, great for team members switching projects that use different tech stacks, and prepare us all to respond quickly to new opportunities (or negatively fortuitous developments). The less siloed we are, the more of a community we are, and the more resilient we are to the slings and arrows of outrageous fortune.

Again, perhaps not the _only_ thing that can be done, or should be done, but I firmly believe it's a _huge_ step in the right direction.

But speaking of smaller-scale failures, this repository that you've found is one of them. I tried to help get this statement in-place a few months ago, even creating this _DRAFT_ repository, but the effort came to a standstill. I chose to instead focus on other things (Hub, Pages, Guides, our internal [Working Groups and Guilds](https://pages.18f.gov/grouplet-playbook/), and other exciting soon-to-be-announced developments), make progress on those, and let this sit for a while until we were ready to give it another go.

That said, the "another go" is imminent, and perhaps another object lesson here is not to allow one stalled effort to halt progress on an array of parallel efforts. Sometimes the way forward is to give one thing a rest, spend time and energy on other things, and come back with a fresh and open mind.

**Comment by anthonygarvan** [comment]
Thanks @mbland for the prompt and thoughtful response. Yes, it seems like you & the team have been working very hard on maintaining a diverse and (extremely!) open environment that should lead to success. My thought with this question was not around how to avoid failure (eg., diversity, openness, collaboration, agile, no silos, user-centered design), since I believe much of 18F Hub / 18F Pages / 18F Guides are roughly devoted to answering 18F's vision for that. I'm particularly curious about after there's a failure, which is unavoidable if you are trying many things over a period of time, what do people do? How should people feel? What should you tell people? If you feel like you know why the failure happened, how should you speak up (or should you speak up)?

Here are some examples from my experience (not sure if they are fully relevant to 18F),
- Developer spends a sprint on a complex feature, but the business requirements change and the feature needs to be reverted. Do you think of it is just part of doing business and say nothing? Do you think of it as a PM issue and pretend like more planning / communication, or a different PM would have prevented it? Do you go hire a Director of Preventing Reversions? Do you make the dev wear a "reverted" hat for a day? 
- A client has demands for an ambitious project. Nobody even knows if it will be feasible, so you undertake a proof of concept. The proof of concept gets complicated, and it turns out it is possible but many compromises would be required, and the decision is made to kill the project. How is the PoC viewed- as a failure, since no code was delivered, or as a success, since the point was to gain knowledge and that was achieved? 
- A big new feature is developed after close consultation with clients. They say they want it, they love the designs, but when it comes time to really use it, they just... don't. Turns out, they really liked the idea of the feature, but they are just too married to their existing processes to really change. I know that Agile strives to mitigate this risk but pushing out small changes and working iteratively, but sometimes people will give feedback like "this is a great start, but I will only start using it once it has X." Then once it has X, they say "What it really needs to replace my process is Y and Z," etc.. In other words, even with great methodologies, user adoption can still be poor or non-existent. How should people feel in that case - is someone to blame? Should a process change, or is this viewed as just another way not to make a light bulb, i.e. part of a creative process which involves trial and error?     

Also, +100 to "another go" - I love this idea of having the core values a living, collaborative effort rather than something issued from the top down.

**Comment by wslack** [comment]
> I'm particularly curious about after there's a failure, which is unavoidable if you are trying many things over a period of time, what do people do? How should people feel? What should you tell people? If you feel like you know why the failure happened, how should you speak up (or should you speak up)?

This is something I'm also thinking about, and I think the answer for us, in part, is iteration - recognize the failure as a learning opportunity, assume good faith of all parties, and modify process to prevent the issue (or at least recognize it). It's hard to codify a particular set of "rules" of guidelines since every situation is so different, but I think we've had some success on that front.

For me personally, it's also helpful to expect low points - issues can be difficult, but a lack of perfection hopefully doesn't shock anyone.

**Comment by anthonygarvan** [comment]
@wslack That's a very appealing & healthy approach. No, I wouldn't expect the answer here to be a detailed list of rules for every type of failure, what you stated was exactly the type of thing I was getting at. While iteration & process changes are key part of responding to failure, a lot of times the failures that hit morale the hardest are those that really are outside of your control and that you *can't* really learn from. For example, one time I was working for a startup whose main goal was to predict hurricane landfall on the East Coast, and we had to close shop because we got hit by hurricane Sandy. What can you really learn from that? In your case, you may build a great product to support or implement a law, only to have the law struck down by SCOTUS. In situations like that, having a culture that does not tolerate or understand failure can lead to a mass exodus.

**Comment by wslack** [comment]
> a lot of times the failures that hit morale the hardest are those that really are outside of your control and that you can't really learn from.

I think part of the hope for 18F is that we can form a large enough "critical mass" to help overcome some challenges that people might be more "stuck" by when working in 1s and 2s at other agencies. There are so many people, with so much good energy, and so many good ideas - but a lot of times there are limiting circumstances.

However, we will hit those as well - and you're right that it can be tough to build in resiliency against that.

**Comment by mbland** [comment]
And my point wasn't that we're trying to avoid failure, but that by building an environment in which transparency and collaboration is encouraged and regularly practiced--so that the iterative learning Will speaks of is expected, adequately preserved, and built upon, and a sense of community is built before it's needed--we aim to provide a cultural buffer that limits the shock of unforeseen circumstances, wherever those circumstances fall along the spectrum from "teachable moments" to "shit happens".

**Comment by wslack** [comment]
:+1:

**Comment by anthonygarvan** [comment]
Very well said Mike & Will. Thanks for the discussion, very informative.

**Comment by melodykramer** [comment]
I really like the way @cmc333333 talks about adapting a product [here](https://18f.gsa.gov/2015/04/09/flexibility-when-releasing-a-new-product-peace-corps-new-donation-platform/) to fit requirements in a specific time period.

**Comment by anthonygarvan** [comment]
@melodykramer @cmc333333 Agreed, that's a great retrospective. Really demonstrates how you guys respond to setbacks under tight constraints.

**Comment by melodykramer** [comment]
Yeah, it's really nice that we can build something and then also talk openly about the process of building something.

**Comment by NoahKunin** [comment]
Love the thread, closing down as part of normal repo O&M. Feel free to re-open or PR based on the above.
